### ISSUE TITLE
automatische Veröffentlichung 

### ISSUE THREAD

**Issue by enidank** [nueww/tw_nueww#17]
System veröffentlicht Artikel automatisch; zeitgesteuert

**Comment by kftw** [comment]
Erledigt - mit Feldern "Start", "Stop" im Karteireiter "Zugriff" steuerbar.

**Comment by kftw** [comment]
@enidank 

Bitte kurze Info: Was ist der Unterschied zu #15 "Artikel vorplanen"? Oder ist das gleiche gemeint?

**Comment by enidank** [comment]
@kftw 
mit vorplanen ist das Einstellen in Typo3 gemeint. Also entweder unsere eigenen Inhalte einfügen und vorbereiten, sodass sie zur Veröffentlichung bereit sind, oder noch mal über die des Gastautoren drüberschauen und ggfs. Änderungen vornehmen (Zwischenüberschriften einfügen, etc.) 
--> Ziel des Vorplanens ist, dass der Artikel anschließend zur Veröffentlichung bereit und im Grunde mit einem entsprechenden Datum in unseren Redaktionsplan übernommen werden kann.

**Comment by kftw** [comment]
Cool, dann kann dieser Issue geschlossen werden 👍
