### ISSUE TITLE
manuelle Veröffentlichung

### ISSUE THREAD

**Issue by enidank** [nueww/tw_nueww#18]
Admin veröffentlicht Artikel manuell

**Comment by kftw** [comment]
@enidank Bitte kurz erklären: Ist hier das "ganz normale" Erstellen und Freischalten durch TYPO3-Redakteure gemeint? Das geht bereits.

**Comment by enidank** [comment]
Ja, genau. 
War eine der User Stories zum Epic Blog. Ist aber im Grunde keine Aufgabe, da es aktuell ja schon so geschieht. 
Wird die manuelle Veröffentlichung trotz der nun auch möglichen Automatisierung als Alternative beibehalten?

**Comment by kftw** [comment]
@enidank 
Jup, geht natürlich beides. Issue wird geschlossen 😎
